version: '3'

services:
  postgres:
    image: mdillon/postgis
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - /volumes/docker_volumes/postgresql:/var/lib/postgresql/data
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
